== Representation METS descriptive metadata section (element dmdSec)

The Representation may contain additional descriptive metadata within the metadata/descriptive folder as described in the CSIP. It is recommended however that Patient Clinical Information related to the Patient Cases that can contain clinical information (diagnoses, conditions, procedures, allergies, family history, care plans) such as can be found in ISO 13606footnote:iso13606[] or the HL7 FHIR Clinical Modulesfootnote:clinical[] and that has been extracted from the source EMR system is included within each individual Patient Record in the repname/data folder, such as to simplify separation of Patient records into individual SIPs at the Archive. Use of metadata standards and codings (e.g. International Classification of Diseases ICDfootnote:ICD[https://www.who.int/classifications/icd/en/], Systematized Nomenclature of Medicine, SNOMED CTfootnote:Snomed[https://www.snomed.org], is encouraged. Where used, references to the specific schemas os resources should be given together with relevant version information.
